FROM python:3.9-alpine

# See https://stackoverflow.com/questions/49118579/alpine-dockerfile-advantages-of-no-cache-vs-rm-var-cache-apk 
# See https://gist.github.com/orenitamar/f29fb15db3b0d13178c1c4dd611adce2
# Numpy https://stackoverflow.com/questions/57763773/install-numpy-requirement-in-a-dockerfile-results-in-error
RUN apk --no-cache add \ 
    gcc \
    git \ 
    gfortran \ 
    musl-dev

#valgrind git python  vim libz-dev

#Creating directories
RUN mkdir /home/packages/ \
    && cd /home/packages/ \
    && git clone https://github.com/romanzes637/gmsh_scripts.git /home/packages/gmsh_scripts/
RUN echo $'\
gmsh==4.8.4 \n\
numpy==1.19.5 \n\
optuna==2.10.0 \n\
plotly==5.5.0 \n\
scikit-learn==1.0.2 \n\
pandas==1.3.5' > /home/packages/gmsh_scripts/requirements_ml.txt
RUN cd /home/packages/gmsh_scripts/ && pip3 install --no-cache-dir -r requirements_ml.txt 
RUN cd /home/packages/gmsh_scripts/ && pip3 install --no-cache-dir -r requirements_postgres.txt 

#RUN ls
#RUN pip3 install -r requirements_ml.txt
#RUN pip3 install psycopg2
#RUN cd /home/packages/gmsh_scripts/test/ml/optuna_postgresql/ && python3 test.py
#RUN python3 test.py

#Setting environment variables
#ENV PETSC_DIR=/home/packages/petsc
#ENV SLEPC_DIR=/home/packages/slepc
#ENV PETSC_ARCH=arch-linux2-c-debug
#ENV FENIA_DIR=/home/packages/OpenFEM-0.0.x
#ENV PATH=$FENIA_DIR/cmake-build-debug/bin:$PATH
#ENV LD_LIBRARY_PATH=/home/packages/petsc/arch-linux2-c-debug/lib/:$LD_LIBRARY_PATH

#Downloading PETSC SLEPC OpenFEM into /home/packages
#RUN git clone -b maint https://bitbucket.org/petsc/petsc /home/packages/petsc
#RUN git clone -b maint https://bitbucket.org/slepc/slepc /home/packages/slepc

#RUN git clone git@svn100.ibrae:/home/git/opf/OpenFEM-0.0.x.git /home/packages/OpenFEM-0.0.x

#Configure\make for PETSC
#RUN cd /home/packages/petsc; ./configure --with-cc=gcc --with-cxx=g++ with-fc=0 --download-f2cblaslapack --download-mpich
#RUN cd /home/packages/petsc; make PETSC_DIR=/home/packages/petsc PETSC_ARCH=arch-linux2-c-debug all
#RUN cd /home/packages/petsc; make PETSC_DIR=/home/packages/petsc PETSC_ARCH=arch-linux2-c-debug check
#RUN cd /home/packages/petsc; make all test
#Configure\make for SLEPC
#RUN cd /home/packages/slepc; ./configure
#RUN cd /home/packages/slepc; make SLEPC_DIR=/home/packages/slepc PETSC_DIR=/home/packages/petsc PETSC_ARCH=arch-linux2-c-debug
#RUN cd /home/packages/slepc; make PETSC_DIR=/home/packages/petsc PETSC_ARCH=arch-linux2-c-debug check
#RUN cd /home/packages/slepc; make all test
